apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: dev
  labels:
    app: todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: estebanmorenoit/my-web-app
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: todo-configmap
