apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: dev
  labels:
    app: todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: estebanmorenoit/my-web-app
          ports:
            - containerPort: 3000
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: password
