apiVersion: v1
kind: Service
metadata:
  name: netflix-clone-service
spec:
  type: LoadBalancer
  selector:
    app: netflix-clone-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080