version: "3.9"
services:
##
##
##_______SYSTEM_____
##____________________ Portainer [SYSTEM/Docker]
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERDIR/portainer/data:/data
    ports:
      - 9000:9000
##
##
##________MEDIA________
##_____________________ Jellyfin [MEDIA/Library] 
  jellyfin:
    container_name: jellyfin
    image: cr.hotio.dev/hotio/jellyfin:latest
    restart: always
    ports:
      - 8096:8096
##
##
##________TOOLS________
##_____________________ VS Code
  code-server:
    container_name: code-server
    image: lscr.io/linuxserver/code-server:latest
    restart: always
    volumes:
      - $DOCKERDIR/code-server/config:/config
    environment:
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    ports:
      - 8443:8443
##
##
##________DEVOPS________
##
##_____________________ Jenkins
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    restart: always
    volumes:
      - $DOCKERDIR/jenkins/config:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    ports:
      - 8080:8080
      - 50000:50000