apiVersion: v1
kind: Service
metadata:
  name: django-todo-app-service
spec:
  type: LoadBalancer
  selector:
    app: django-todo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
